title = "HOME"
baseURL = "https://yjloong.github.io/"
languageCode = "zh"
theme = 'ananke'
resourceDir = "./resources"

DefaultContentLanguage = "zh"
SectionPagesMenu = "main"
#Paginate = 3                  # this is set low for demonstrating with dummy content. Set to a higher number

googleAnalytics = ""
enableRobotsTXT = true

contentDir = "content"

[pagination]
pagerSize = 3

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[params]
text_color = ""
author = ""
favicon = "images/logo.png"
site_logo = ""
description = "能吃能睡"
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-black"
recent_posts_number = 3
omit_header_text = true
show_reading_time = true

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 1

[[params.ananke_socials]]
name = "twitter"
#url = "https://twitter.com/GoHugoIO"

